### ISSUE TITLE
Question regarding the code

### ISSUE THREAD

**Issue by zhangdan8962** [UCSD-AI4H/CERT#1]
Hi,

I am wondering what is the purpose for the following line.
https://github.com/UCSD-AI4H/CERT/blob/1b3c52f002406d9b4616678aa2a10b66a8830f1d/moco/builder.py#L41

Since you already indicate the num_labels in
 `self.encoder_q = BertForSequenceClassification.from_pretrained(
            './pretrained/',  # Use the 12-layer BERT model, with an uncased vocab.
            num_labels=dim,  # The number of output labels--2 for binary classification.
            # You can increase this for multi-class tasks.
            output_attentions=False,  # Whether the model returns attentions weights.
            output_hidden_states=False,  # Whether the model returns all hidden-states.
        )`

**Comment by JiayuanDing100** [comment]
Hi Dan,
Since you asked the question through email thread separately and got the response.

I just move the response here in case other ppl need it.
you can delete the sentence of replacing the classifier by setting num_labels. They are all same.

**Comment by JiayuanDing100** [comment]
resolved
