### ISSUE TITLE
is it possible to train on only one GPU

### ISSUE THREAD

**Issue by ShengleiH** [UCSD-AI4H/CERT#6]
When I followed the script "CUDA_VISIBLE_DEVICES=0 python MOCO.py" in README to train a moco model, I got the assertion error as follows: "AssertionError: Default process group is not initialized". Therefore, I am wondering how do you trained it with only one GPU? @ColeFang @JiayuanDing100

**Comment by ShengleiH** [comment]
I have solved it. Since in NLP, it is not necessary to use BatchNorm, the shuffle BatchNorm module which relies heavily on multi-GPU could be removed.

**Comment by cloudyskyy** [comment]
Indeed, it is not necessary to use BatchNorm. However, I am just wondering if removing shuffle BatchNorm would weaken the performance of moco? Could you please tell me how your result ends? I am also trapped in the situation where only one single gpu is avaliable. Thank you!
